trigger:
  branches:
    include:
      - main
    exclude:
      - Feature/**  
  paths:
    include:
      - main.tf
    exclude:
      - backend.sh
      - provider.tf

pool:
  name: Agents
  # demands: agent.name -equals <name of agent>

# variables: 

stages:
  - stage: 
    displayName: Build and Deploy
    jobs:
      - job: 
        displayName: Build and Deploy
        steps:
          - task: TerraformInstaller@1
            displayName: terraform installer
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTask@5
            displayName: Terraform Init
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'DevAzureService'
              backendAzureRmOverrideSubscriptionID: 'cefa80e5-9af0-4e4a-9f43-e0a0491a5473'
              backendAzureRmResourceGroupName: 'prince-env-rg'
              backendAzureRmStorageAccountName: 'princeenvstg24284'
              backendAzureRmContainerName: 'princecontainer'
              backendAzureRmKey: 'prince.tfstate'
          - task: TerraformTask@5
            displayName: Terraform Validate
            inputs:
              provider: 'azurerm'
              command: 'validate'
          - task: TerraformTask@5
            displayName: Terraform Plan
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'DevAzureService'

